Example for Commander
nodejs/examples pull request #32
Opened 2020-11-08 14:48 UTC by Thiruppathi

CLI built with [commander](https://www.npmjs.com/package/commander) to generate fake names using [faker](https://www.npmjs.com/package/faker)

2020-11-09 18:29 UTC, rodion-arr approved these changes
Nice 👍

2020-11-09 18:29 UTC, rodion-arr commented on cli/commander/fake-names-generator/README.md
> +You may want to run `npm uninstall -g` # to uninstall it.
```suggestion
You may want to run `npm uninstall -g` to uninstall it.
```

2020-11-09 18:29 UTC, rodion-arr commented on cli/commander/fake-names-generator/README.md
> +CLI built with [commander](https://www.npmjs.com/package/commander) to generate fake names using [faker](https://www.npmjs.com/package/faker)
Is it ok to have markdown in `package.json` description and as result in `--help` command? Not sure I've seen it before in other packages.

2020-11-09 19:13 UTC, rodion-arr commented
It's failing on Windows due to `:` in JSON filenames.

2020-11-09 20:04 UTC, Thiruppathi commented
> It's failing on Windows due to `:` in JSON filenames.

Haaa. Thanks. Will fix it.

2020-11-09 20:12 UTC, Thiruppathi commented on cli/commander/fake-names-generator/README.md
> +CLI built with [commander](https://www.npmjs.com/package/commander) to generate fake names using [faker](https://www.npmjs.com/package/faker)
It doesn't throw any error on linting; thought could be handy to click the url and navigate from cli. Am not sure as well. :)

2020-11-09 21:07 UTC, bnb requested changes
Left some initial feedback. Biggest thing here is to remove the gendered names as an option  - it may be worth adding something in their place.

2020-11-09 21:07 UTC, bnb commented on cli/commander/fake-names-generator/README.md
> +  -g, --gender <option>    Specify gender (default: "female")
Let's try to be agnostic and inclusive and get rid of gender as an option here. Perhaps replacing with short/long, first letter, or something like that.

2020-11-09 21:07 UTC, bnb commented on cli/commander/fake-names-generator/README.md
> +        $ fake-names-generator -g male          # generates a male full name
Again, let's get rid of gender in the project. Good implementation but there's better features we could build.

2020-11-09 21:07 UTC, bnb commented on cli/commander/fake-names-generator/README.md
> +
```suggestion
```

Unnecessary blank line.

2020-11-09 21:07 UTC, bnb commented on cli/commander/fake-names-generator/README.md
> +You may want to run `npm uninstall -g` to uninstall it.
```suggestion
You may want to run `npm uninstall -g` from the project directory to uninstall it.
```

Adds a bit more context.

2020-11-09 21:07 UTC, bnb commented on cli/commander/fake-names-generator/package.json
> +    "faker": "^5.1.0"
I'd recommend using a module other than faker here.

2020-11-10 13:04 UTC, Thiruppathi commented on cli/commander/fake-names-generator/README.md
> +        $ fake-names-generator -g male          # generates a male full name
Sure. will update it

2020-11-13 18:22 UTC, bnb commented on .gitignore
> +*.code-workspace
```suggestion
```

Always good to have a blank line at the end of your files if using Git 👍🏻

2020-11-13 18:56 UTC, bnb commented on cli/commander/fake-names-generator/README.md
> +CLI built with [commander](https://www.npmjs.com/package/commander) to generate fake names using [ChanceJS](https://www.npmjs.com/package/chance)
```suggestion
CLI built with [commander](https://www.npmjs.com/package/commander) to generate fake names using [Chance](https://www.npmjs.com/package/chance)
```

Looking around their README, it seems the only time `ChanceJS` is in the domain. Let's change it to `Chance`, which is how they describe it in prose.

2020-11-13 18:56 UTC, bnb commented on cli/commander/fake-names-generator/README.md
> +CLI built with [commander](https://www.npmjs.com/package/commander) to generate fake names using [ChanceJS](https://www.npmjs.com/package/chance)
```suggestion
CLI built with [commander](https://www.npmjs.com/package/commander) to generate fake names using [Chance](https://www.npmjs.com/package/chance)
```

Looking around their README, it seems the only time `ChanceJS` is in the domain. Let's change it to `Chance`, which is how they describe it in prose.

2020-11-13 19:16 UTC, bnb commented on cli/commander/fake-names-generator/package.json
> +  "description": "CLI built with [commander](https://www.npmjs.com/package/commander) to generate fake names using [ChanceJS](https://www.npmjs.com/package/chance)",
```suggestion
CLI built with [commander](https://www.npmjs.com/package/commander) to generate fake names using [Chance](https://www.npmjs.com/package/chance)
```

Looking around their README, it seems the only time `ChanceJS` is in the domain. Let's change it to `Chance`, which is how they describe it in prose.

2020-12-08 20:52 UTC, bnb approved these changes

2020-12-09 15:56 UTC, merged